version: '3.9'

services:

  postgres:

    image: pgvector/pgvector:pg16

    container_name: semantic-postgres

    restart: always

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: semanticdb

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: