spring:

  application:
    name: semantic-cache

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    default_schema: semantic_cache
    username: postgres
    password: netcracker
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

    properties:
        hibernate:
          default_schema: semantic_cache


  ai:
    openai:
      api-key: 123

