spring:

  application:
    name: semantic-cache

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=semantic_cache
    default_schema: semantic_cache
    username: postgres
    password: postgres@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

    properties:
        hibernate:
          default_schema: semantic_cache


  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
        chat:
          options:
            model: gpt-4.1-mini

